#!/usr/bin/env bash
set -euo pipefail

INPUT_CSV="data/input/sample.csv"
REPORT_DIR="reports"
REPORT_FILE="$REPORT_DIR/analysis_report.md"

echo "=== Generating report from $INPUT_CSV ==="

mkdir -p "$REPORT_DIR"

python - << 'PYCODE'
import pandas as pd
from project_alpha.analysis import analyze

df = pd.read_csv("$INPUT_CSV")
summary = analyze(df)

with open("$REPORT_FILE", "w") as f:
    f.write("# Analysis Report\n\n")
    f.write("Generated by Project Alpha\n\n")
    f.write("## Summary\n")
    for key, value in summary.items():
        f.write(f"- **{key}**: {value}\n")
PYCODE

echo "Report written to $REPORT_FILE"
echo "=== Report generation complete ==="
